$r  = [char]0xFFFD
$rr = "$r$r"

$base = if ($PSScriptRoot) { $PSScriptRoot } else { (Get-Location).Path }
$files = Get-ChildItem -Path $base -Recurse -Filter *.html |
    ForEach-Object {
        $_.FullName.Substring($base.Length + 1).Replace('\', '/')
    } |
    Sort-Object

# Ordered hashtable — longer/more-specific patterns FIRST
$repl = [ordered]@{}

# ── Names ────────────────────────────────────────────────────────────────────
$repl["Jo${r}o Basto"] = 'Jo&#227;o Basto'
$repl["Jo${r}o"]       = 'Jo&#227;o'
$repl["Lu${r}sa"]      = 'Lu&#237;sa'

# ── Copyright symbol © ───────────────────────────────────────────────────────
$repl["${r} 2025"] = '&#169; 2025'

# ── Title / meta em-dash separators ──────────────────────────────────────────
$repl[" ${r} Rounds Academy"] = ' &#8212; Rounds Academy'
$repl["Academy ${r} Conhe"]   = 'Academy &#8212; Conhe'
$repl["Academy ${r} Entre"]   = 'Academy &#8212; Entre'
$repl["Academy ${r} Meet"]    = 'Academy &#8212; Meet'
$repl["Academy ${r} A hist"]  = 'Academy &#8212; A hist'
$repl["Academy ${r} aprenda"] = 'Academy &#8212; aprenda'
$repl["Academy ${r} Treino"]  = 'Academy &#8212; Treino'
$repl["Academy ${r} Learn"]   = 'Academy &#8212; Learn'

# ── Credential dash ──────────────────────────────────────────────────────────
$repl["II ${r} 2 Star"] = 'II &#8212; 2 Star'

# ── Navigation ───────────────────────────────────────────────────────────────
$repl["In${r}cio"]     = 'In&#237;cio'
$repl["in${r}cio"]     = 'in&#237;cio'
$repl["Hor${r}rio"]    = 'Hor&#225;rio'
$repl["hor${r}rio"]    = 'hor&#225;rio'
$repl["Portugu${r}s"]  = 'Portugu&#234;s'
$repl["portugu${r}s"]  = 'portugu&#234;s'
$repl["Portugu${r}sa"] = 'Portugu&#234;sa'
$repl["portugu${r}sa"] = 'portugu&#234;sa'

# ── SOBRE NÓS heading ────────────────────────────────────────────────────────
$repl["SOBRE N${r}S"] = 'SOBRE N&#211;S'

# ── Double-FFFD: -ção singular (ç+ã) ─────────────────────────────────────────
$repl["competi${rr}o"]   = 'competi&#231;&#227;o'
$repl["Competi${rr}o"]   = 'Competi&#231;&#227;o'
$repl["forma${rr}o"]     = 'forma&#231;&#227;o'
$repl["Forma${rr}o"]     = 'Forma&#231;&#227;o'
$repl["evolu${rr}o"]     = 'evolu&#231;&#227;o'
$repl["Evolu${rr}o"]     = 'Evolu&#231;&#227;o'
$repl["supera${rr}o"]    = 'supera&#231;&#227;o'
$repl["Supera${rr}o"]    = 'Supera&#231;&#227;o'
$repl["constru${rr}o"]   = 'constru&#231;&#227;o'
$repl["Constru${rr}o"]   = 'Constru&#231;&#227;o'
$repl["Gradua${rr}o"]    = 'Gradua&#231;&#227;o'
$repl["gradua${rr}o"]    = 'gradua&#231;&#227;o'
$repl["Navega${rr}o"]    = 'Navega&#231;&#227;o'
$repl["navega${rr}o"]    = 'navega&#231;&#227;o'
$repl["aten${rr}o"]      = 'aten&#231;&#227;o'
$repl["Aten${rr}o"]      = 'Aten&#231;&#227;o'
$repl["posi${rr}o"]      = 'posi&#231;&#227;o'
$repl["Posi${rr}o"]      = 'Posi&#231;&#227;o'
$repl["movimenta${rr}o"] = 'movimenta&#231;&#227;o'
$repl["coordena${rr}o"]  = 'coordena&#231;&#227;o'
$repl["combina${rr}o"]   = 'combina&#231;&#227;o'
$repl["Combina${rr}o"]   = 'Combina&#231;&#227;o'
$repl["Op${rr}o"]        = 'Op&#231;&#227;o'
$repl["op${rr}o"]        = 'op&#231;&#227;o'
$repl["muscula${rr}o"]   = 'muscula&#231;&#227;o'
$repl["Muscula${rr}o"]   = 'Muscula&#231;&#227;o'
$repl["progres${rr}o"]   = 'progres&#231;&#227;o'
$repl["Progres${rr}o"]   = 'Progres&#231;&#227;o'
$repl["prepara${rr}o"]   = 'prepara&#231;&#227;o'
$repl["Prepara${rr}o"]   = 'Prepara&#231;&#227;o'
$repl["na${rr}o"]        = 'na&#231;&#227;o'
$repl["cria${rr}o"]      = 'cria&#231;&#227;o'
$repl["Cria${rr}o"]      = 'Cria&#231;&#227;o'
$repl["informa${rr}o"]   = 'informa&#231;&#227;o'
$repl["Informa${rr}o"]   = 'Informa&#231;&#227;o'
$repl["situa${rr}o"]     = 'situa&#231;&#227;o'
$repl["composi${rr}o"]   = 'composi&#231;&#227;o'
$repl["Composi${rr}o"]   = 'Composi&#231;&#227;o'
$repl["Dura${rr}o"]      = 'Dura&#231;&#227;o'
$repl["dura${rr}o"]      = 'dura&#231;&#227;o'
$repl["qualifica${rr}o"] = 'qualifica&#231;&#227;o'
$repl["Qualifica${rr}o"] = 'Qualifica&#231;&#227;o'
$repl["respira${rr}o"]   = 'respira&#231;&#227;o'
$repl["Respira${rr}o"]   = 'Respira&#231;&#227;o'
$repl["associa${rr}o"]   = 'associa&#231;&#227;o'
$repl["Associa${rr}o"]   = 'Associa&#231;&#227;o'

# ── Double-FFFD: -ções plural (ç+õ) ──────────────────────────────────────────
$repl["combina${rr}es"] = 'combina&#231;&#245;es'
$repl["Combina${rr}es"] = 'Combina&#231;&#245;es'
$repl["posi${rr}es"]    = 'posi&#231;&#245;es'
$repl["Posi${rr}es"]    = 'Posi&#231;&#245;es'
$repl["forma${rr}es"]   = 'forma&#231;&#245;es'
$repl["Forma${rr}es"]   = 'Forma&#231;&#245;es'
$repl["informa${rr}es"] = 'informa&#231;&#245;es'
$repl["Informa${rr}es"] = 'Informa&#231;&#245;es'
$repl["competi${rr}es"] = 'competi&#231;&#245;es'
$repl["Competi${rr}es"] = 'Competi&#231;&#245;es'
$repl["sess${rr}es"]    = 'sess&#245;es'
$repl["Sess${rr}es"]    = 'Sess&#245;es'

# ── Single-FFFD: ã ───────────────────────────────────────────────────────────
$repl["vis${r}o"]    = 'vis&#227;o'
$repl["Vis${r}o"]    = 'Vis&#227;o'
$repl["Gest${r}o"]   = 'Gest&#227;o'
$repl["gest${r}o"]   = 'gest&#227;o'
$repl["miss${r}o"]   = 'miss&#227;o'
$repl["Miss${r}o"]   = 'Miss&#227;o'
$repl["sess${r}o"]   = 'sess&#227;o'
$repl["Sess${r}o"]   = 'Sess&#227;o'
$repl["sess${r}es"]  = 'sess&#245;es'
$repl["Sess${r}es"]  = 'Sess&#245;es'
$repl["tens${r}o"]   = 'tens&#227;o'
$repl["Tens${r}o"]   = 'Tens&#227;o'
$repl["paix${r}o"]   = 'paix&#227;o'
$repl["Paix${r}o"]   = 'Paix&#227;o'
$repl["ent${r}o"]    = 'ent&#227;o'
$repl["Ent${r}o"]    = 'Ent&#227;o'
$repl["padr${r}o"]   = 'padr&#227;o'
$repl["Padr${r}o"]   = 'Padr&#227;o'
$repl["campe${r}es"] = 'campe&#245;es'
$repl["Campe${r}es"] = 'Campe&#245;es'
$repl["CAMPE${r}ES"] = 'CAMPE&#213;ES'
$repl["campe${r}o"]  = 'campe&#227;o'
$repl["Campe${r}o"]  = 'Campe&#227;o'
$repl["CAMPE${r}O"]  = 'CAMPE&#195;O'
$repl["m${r}os"]     = 'm&#227;os'
$repl["n${r}o"]      = 'n&#227;o'
$repl["s${r}o criados"]     = 's&#227;o criados'
$repl["s${r}o bem-vindos"]  = 's&#227;o bem-vindos'
$repl["s${r}o ineg"]        = 's&#227;o ineg'
$repl["s${r}o v"]           = 's&#227;o v'
$repl["s${r}o estruturadas"]= 's&#227;o estruturadas'
$repl["s${r}o bem"]         = 's&#227;o bem'

# ── Single-FFFD: á ───────────────────────────────────────────────────────────
$repl["hist${r}ria"]    = 'hist&#243;ria'
$repl["Hist${r}ria"]    = 'Hist&#243;ria'
$repl["atl${r}tica"]    = 'atl&#233;tica'
$repl["tr${r}s"]        = 'tr&#225;s'
$repl["Ador${r}vamos"]  = 'Ador&#225;vamos'
$repl["ador${r}vamos"]  = 'ador&#225;vamos'
$repl["S${r}bado"]      = 'S&#225;bado'
$repl["s${r}bado"]      = 's&#225;bado'
$repl["m${r}xima"]      = 'm&#225;xima'
$repl["M${r}xima"]      = 'M&#225;xima'
$repl["m${r}ximo"]      = 'm&#225;ximo'
$repl["M${r}ximo"]      = 'M&#225;ximo'
$repl["m${r}ximos"]     = 'm&#225;ximos'
$repl["saud${r}vel"]    = 'saud&#225;vel'
$repl["Saud${r}vel"]    = 'Saud&#225;vel'
$repl["h${r}bitos"]     = 'h&#225;bitos'
$repl["H${r}bitos"]     = 'H&#225;bitos'
$repl["car${r}cter"]    = 'car&#225;cter'
$repl["Car${r}cter"]    = 'Car&#225;cter'
$repl["car${r}ter"]     = 'car&#225;ter'
$repl["Gin${r}sios"]    = 'Gin&#225;sios'
$repl["gin${r}sios"]    = 'gin&#225;sios'
$repl["Gin${r}sio"]     = 'Gin&#225;sio'
$repl["gin${r}sio"]     = 'gin&#225;sio'
$repl["formul${r}rio"]  = 'formul&#225;rio'
$repl["Formul${r}rio"]  = 'Formul&#225;rio'

# ── Single-FFFD: é / ê ───────────────────────────────────────────────────────
$repl["acad${r}mica"]   = 'acad&#234;mica'
$repl["Acad${r}mica"]   = 'Acad&#234;mica'
$repl["certifica${rr}o"]= 'certifica&#231;&#227;o'
$repl["compet${r}ncias"]= 'compet&#234;ncias'
$repl["Compet${r}ncias"]= 'Compet&#234;ncias'
$repl["compet${r}ncia"] = 'compet&#234;ncia'
$repl["Compet${r}ncia"] = 'Compet&#234;ncia'
$repl["consist${r}ncia"]= 'consist&#234;ncia'
$repl["Consist${r}ncia"]= 'Consist&#234;ncia'
$repl["excel${r}ncia"]  = 'excel&#234;ncia'
$repl["Excel${r}ncia"]  = 'Excel&#234;ncia'
$repl["frequ${r}ncia"]  = 'frequ&#234;ncia'
$repl["Frequ${r}ncia"]  = 'Frequ&#234;ncia'
$repl["experi${r}ncia"] = 'experi&#234;ncia'
$repl["Experi${r}ncia"] = 'Experi&#234;ncia'
$repl["exig${r}ncia"]   = 'exig&#234;ncia'
$repl["Exig${r}ncia"]   = 'Exig&#234;ncia'
$repl["consci${r}ncia"] = 'consci&#234;ncia'
$repl["Consci${r}ncia"] = 'Consci&#234;ncia'
$repl["ci${r}ncia"]     = 'ci&#234;ncia'
$repl["Ci${r}ncia"]     = 'Ci&#234;ncia'
$repl["resist${r}ncia"] = 'resist&#234;ncia'
$repl["Resist${r}ncia"] = 'Resist&#234;ncia'
$repl["paci${r}ncia"]   = 'paci&#234;ncia'
$repl["Paci${r}ncia"]   = 'Paci&#234;ncia'
$repl["pres${r}n"]      = 'pres&#234;n'
$repl["estrat${r}gica"] = 'estrat&#233;gica'
$repl["Estrat${r}gica"] = 'Estrat&#233;gica'
$repl["estrat${r}gico"] = 'estrat&#233;gico'
$repl["m${r}todo"]      = 'm&#233;todo'
$repl["M${r}todo"]      = 'M&#233;todo'
$repl["d${r}cadas"]     = 'd&#233;cadas'
$repl["D${r}cadas"]     = 'D&#233;cadas'
$repl["d${r}cada"]      = 'd&#233;cada'
$repl["D${r}cada"]      = 'D&#233;cada'
$repl["atrav${r}s"]     = 'atrav&#233;s'
$repl["Atrav${r}s"]     = 'Atrav&#233;s'
$repl["al${r}m"]        = 'al&#233;m'
$repl["Al${r}m"]        = 'Al&#233;m'
$repl["tamb${r}m"]      = 'tamb&#233;m'
$repl["Tamb${r}m"]      = 'Tamb&#233;m'
$repl["ningu${r}m"]     = 'ningu&#233;m'
$repl["Ningu${r}m"]     = 'Ningu&#233;m'
$repl["T${r}cnicas"]    = 'T&#233;cnicas'
$repl["t${r}cnicas"]    = 't&#233;cnicas'
$repl["T${r}cnica"]     = 'T&#233;cnica'
$repl["t${r}cnica"]     = 't&#233;cnica'
$repl["T${r}cnico"]     = 'T&#233;cnico'
$repl["t${r}cnico"]     = 't&#233;cnico'
$repl["at${r} "]        = 'at&#233; '
$repl["at${r}."]        = 'at&#233;.'
$repl["n${r}vel"]       = 'n&#237;vel'
$repl["N${r}vel"]       = 'N&#237;vel'
$repl["n${r}veis"]      = 'n&#237;veis'
$repl["N${r}veis"]      = 'N&#237;veis'

# ── Single-FFFD: í ───────────────────────────────────────────────────────────
$repl["P${r}s-"]        = 'P&#243;s-'
$repl["p${r}s-"]        = 'p&#243;s-'
$repl["benef${r}cios"]  = 'benef&#237;cios'
$repl["Benef${r}cios"]  = 'Benef&#237;cios'
$repl["princ${r}pios"]  = 'princ&#237;pios'
$repl["Princ${r}pios"]  = 'Princ&#237;pios'
$repl["princ${r}pio"]   = 'princ&#237;pio'
$repl["dif${r}cil"]     = 'dif&#237;cil'
$repl["Dif${r}cil"]     = 'Dif&#237;cil'
$repl["f${r}sica"]      = 'f&#237;sica'
$repl["F${r}sica"]      = 'F&#237;sica'
$repl["f${r}sico"]      = 'f&#237;sico'
$repl["F${r}sico"]      = 'F&#237;sico'
$repl["f${r}sicos"]     = 'f&#237;sicos'
$repl["cont${r}nuo"]    = 'cont&#237;nuo'
$repl["Cont${r}nuo"]    = 'Cont&#237;nuo'
$repl["Constru${r}da"]  = 'Constru&#237;da'
$repl["constru${r}da"]  = 'constru&#237;da'
$repl["Constru${r}dos"] = 'Constru&#237;dos'
$repl["constru${r}dos"] = 'constru&#237;dos'
$repl["constru${r}mos"] = 'constru&#237;mos'
$repl["Constru${r}mos"] = 'Constru&#237;mos'
$repl["incr${r}vel"]    = 'incr&#237;vel'
$repl["Incr${r}vel"]    = 'Incr&#237;vel'
$repl["j${r}nior"]      = 'j&#250;nior'
$repl["J${r}nior"]      = 'J&#250;nior'
$repl["m${r}nimo"]      = 'm&#237;nimo'
$repl["M${r}nimo"]      = 'M&#237;nimo'
$repl["per${r}odos"]    = 'per&#237;odos'
$repl["Per${r}odos"]    = 'Per&#237;odos'
$repl["t${r}mida"]      = 't&#237;mida'
$repl["T${r}mida"]      = 'T&#237;mida'

# ── Single-FFFD: ó ───────────────────────────────────────────────────────────
$repl["prop${r}sito"]   = 'prop&#243;sito'
$repl["Prop${r}sito"]   = 'Prop&#243;sito'
$repl["pr${r}ximo"]     = 'pr&#243;ximo'
$repl["Pr${r}ximo"]     = 'Pr&#243;ximo'
$repl["aer${r}bico"]    = 'aer&#243;bico'
$repl["contr${r}rio"]   = 'contr&#225;rio'
$repl["precis${r}o"]    = 'precis&#227;o'
$repl["Precis${r}o"]    = 'Precis&#227;o'

# ── Single-FFFD: ç ───────────────────────────────────────────────────────────
$repl["Conhe${r}a"]     = 'Conhe&#231;a'
$repl["conhe${r}a"]     = 'conhe&#231;a'
$repl["come${r}ar"]     = 'come&#231;ar'
$repl["Come${r}ar"]     = 'Come&#231;ar'
$repl["come${r}ou"]     = 'come&#231;ou'
$repl["come${r}a"]      = 'come&#231;a'
$repl["avan${r}ar"]     = 'avan&#231;ar'
$repl["Avan${r}ar"]     = 'Avan&#231;ar'
$repl["avan${r}ados"]   = 'avan&#231;ados'
$repl["Avan${r}ados"]   = 'Avan&#231;ados'
$repl["autoconfian${r}a"]= 'autoconfian&#231;a'
$repl["Autoconfian${r}a"]= 'Autoconfian&#231;a'
$repl["crian${r}a"]     = 'crian&#231;a'
$repl["Crian${r}as"]    = 'Crian&#231;as'
$repl["Confian${r}a"]   = 'Confian&#231;a'
$repl["confian${r}a"]   = 'confian&#231;a'
$repl["Perseveran${r}a"]= 'Perseveran&#231;a'
$repl["perseveran${r}a"]= 'perseveran&#231;a'
$repl["Endere${r}o"]    = 'Endere&#231;o'
$repl["endere${r}o"]    = 'endere&#231;o'
$repl["espa${r}o"]      = 'espa&#231;o'
$repl["Espa${r}o"]      = 'Espa&#231;o'
$repl["seguran${r}a"]   = 'seguran&#231;a'
$repl["Seguran${r}a"]   = 'Seguran&#231;a'
$repl["Ter${r}a"]       = 'Ter&#231;a'
$repl["ter${r}a"]       = 'ter&#231;a'
$repl["for${r}a"]       = 'for&#231;a'
$repl["For${r}a"]       = 'For&#231;a'

# ── Single-FFFD: ú ───────────────────────────────────────────────────────────
$repl["d${r}vidas"]     = 'd&#250;vidas'
$repl["D${r}vidas"]     = 'D&#250;vidas'
$repl["sa${r}de"]       = 'sa&#250;de'
$repl["Sa${r}de"]       = 'Sa&#250;de'
$repl["m${r}sculo"]     = 'm&#250;sculo'
$repl["M${r}sculo"]     = 'M&#250;sculo'
$repl["m${r}sculos"]    = 'm&#250;sculos'

# ── Single-FFFD: õ ───────────────────────────────────────────────────────────
$repl["quest${r}es"]    = 'quest&#245;es'
$repl["Quest${r}es"]    = 'Quest&#245;es'

# ── "é" verb — specific safe contexts ────────────────────────────────────────
$repl["nome ${r} "]         = 'nome &#233; '
$repl[" ${r} uma academia"] = ' &#233; uma academia'
$repl[" ${r} uma crian"]    = ' &#233; uma crian'
$repl[" ${r} uma ferramenta"]= ' &#233; uma ferramenta'
$repl["${r} uma ferramenta"] = '&#201; uma ferramenta'
$repl[" ${r} com essa"]      = ' &#233; com essa'
$repl["${r} com essa"]       = '&#201; com essa'
$repl[" ${r} preciso"]       = ' &#233; preciso'
$repl["${r} preciso"]        = '&#201; preciso'
$repl[" ${r} a base"]        = ' &#233; a base'
$repl[" ${r} a aula"]        = ' &#233; a aula'
$repl["${r} a aula"]         = '&#201; a aula'
$repl[" ${r} a nossa"]       = ' &#233; a nossa'
$repl[" ${r} aberto"]        = ' &#233; aberto'
$repl[" ${r} condicionamento"]= ' &#233; condicionamento'
$repl[" ${r} de tamanho"]    = ' &#233; de tamanho'
$repl[" ${r} ensinada"]      = ' &#233; ensinada'
$repl[" ${r} para quem"]     = ' &#233; para quem'
$repl["${r} para quem"]      = '&#201; para quem'
$repl[" ${r} um dos"]        = ' &#233; um dos'
$repl[" ${r} paciente"]      = ' &#233; paciente'
$repl["${r} a base de"]      = '&#201; a base de'
$repl[" ${r} o que"]         = ' &#233; o que'
$repl[" ${r} tamb"]          = ' &#233; tamb'
$repl[" ${r} exatamente"]    = ' &#233; exatamente'
$repl[" ${r} ensinado"]      = ' &#233; ensinado'
$repl[" ${r} para todos"]    = ' &#8212; para todos'
$repl["Para Quem ${r}"]      = 'Para Quem &#201;?'

# ── "à / às" safe contexts ───────────────────────────────────────────────────
$repl["assistir ${r}s sess${rr}es"] = 'assistir &#224;s sess&#245;es'
$repl["adequados ${r} sua idade"]   = 'adequados &#224; sua idade'
$repl["junta ${r} Rounds Academy"]  = 'junta &#224; Rounds Academy'
$repl["Junta-te ${r} fam${r}lia"]   = 'Junta-te &#224; fam&#237;lia'
$repl["quanto ${r} t${r}cnica"]     = 'quanto &#224; t&#233;cnica'
$repl[" ${r}s sess${rr}es"]         = ' &#224;s sess&#245;es'

# ── Pés (feet) ────────────────────────────────────────────────────────────────
$repl["de p${r}s"]          = 'de p&#233;s'
$repl["de p${r}s,"]         = 'de p&#233;s,'

# ── Schedule dashes ──────────────────────────────────────────────────────────
$repl["Seg${r}Sex"]         = 'Seg&#8211;Sex'
$repl["06:30 ${r} 21:00"]   = '06:30 &#8211; 21:00'
$repl["10:00 ${r} 13:00"]   = '10:00 &#8211; 13:00'
$repl["11:00 ${r} 13:00"]   = '11:00 &#8211; 13:00'
$repl["45 ${r} 60 min"]     = '45 &#8211; 60 min'
$repl["Mapa ${r} R."]       = 'Mapa &#8212; R.'

# ── Content em-dashes ────────────────────────────────────────────────────────
$repl["memberships ${r} estamos"] = 'memberships &#8212; estamos'
$repl[" ${r} estamos"]     = ' &#8212; estamos'
$repl[" ${r} e sparring"]  = ' &#8212; e sparring'
$repl[" ${r} t${r}cnica"]  = ' &#8212; t&#233;cnica'
$repl[" ${r} trazendo"]    = ' &#8212; trazendo'
$repl[" ${r} desde"]       = ' &#8212; desde'
$repl["M${r}e ${r} filho"] = 'M&#227;e &#8212; filho'
$repl["M${r}e ${r} dois filhos"] = 'M&#227;e &#8212; dois filhos'
$repl["Pai ${r} filha"]    = 'Pai &#8212; filha'
$repl["Parent ${r} two boys"] = 'Parent &#8212; two boys'
$repl["Membro desde 2021 ${r} Boxe"] = 'Membro desde 2021 &#8212; Boxe'
$repl["Membro desde 2020 ${r} HIIT Boxing"] = 'Membro desde 2020 &#8212; HIIT Boxing'
$repl["membro ${r} Boxing Kids"] = 'membro &#8212; Boxing Kids'

# ── Footer tagline ────────────────────────────────────────────────────────────
$repl["Onde os campe${r}es s${r}o criados"] = 'Onde os campe&#245;es s&#227;o criados'

# ── Placeholder glyphs ────────────────────────────────────────────────────────
$repl['<div class="achievement-icon">??</div>'] = '<div class="achievement-icon">&#10022;</div>'
$repl['<div class="testimonial-stars">?????</div>'] = '<div class="testimonial-stars">&#9733;&#9733;&#9733;&#9733;&#9733;</div>'

# ── Run replacements ──────────────────────────────────────────────────────────
$utf8 = [System.Text.UTF8Encoding]::new($false)

foreach ($f in $files) {
    $path = Join-Path $base ($f -replace '/', '\')
    if (-not (Test-Path $path)) { Write-Host "SKIP: $f"; continue }

    $content = [System.IO.File]::ReadAllText($path, $utf8)
    $before  = ($content.ToCharArray() | Where-Object { $_ -eq $r } | Measure-Object).Count

    foreach ($key in $repl.Keys) {
        $content = $content.Replace($key, $repl[$key])
    }

    $after = ($content.ToCharArray() | Where-Object { $_ -eq $r } | Measure-Object).Count
    [System.IO.File]::WriteAllText($path, $content, $utf8)
    Write-Host ("{0}: {1} -> {2} FFFD remaining" -f $f, $before, $after)
}

Write-Host "`nDone."
